# Generated by Django 4.0.5 on 2022-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=30)),
                ('custid', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=30)),
                ('pcatid', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('dateoforder', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
