# Generated by Django 4.0.5 on 2022-07-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_stockin'),
    ]

    operations = [
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.CharField(max_length=30)),
                ('storename', models.CharField(max_length=30)),
                ('storeadd', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('gst', models.CharField(max_length=30)),
                ('pan', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
