# Generated by Django 4.0.5 on 2022-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supid', models.CharField(max_length=30)),
                ('supname', models.CharField(max_length=30)),
                ('supadd', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
