# Generated by Django 4.0.5 on 2022-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.CharField(max_length=30)),
                ('custname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('custadd', models.CharField(max_length=30)),
                ('custcity', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
