# Generated by Django 4.0.5 on 2022-07-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billid', models.CharField(max_length=30)),
                ('orderid', models.CharField(max_length=30)),
                ('custid', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=30)),
                ('pcatid', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('dateofbill', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
